---
- hosts: all
  become: true

  roles:
    #- linux_language
    #- official_packages
    - unofficial_packages
    #- git_configure
    #- pip_packages
    #- golang_packages
    #- atom_packages
