---
- hosts: all

  roles:
    - { role: linux_language, become: yes }
    - { role: official_packages, become: yes }
    - { role: unofficial_packages, become: yes }
    - { role: git_configure }
    #- { role: pip_packages, become: yes }
    #- { role: golang_packages }
    #- { role: atom_packages }
