---
become: true
- name: Updating cache and packages
  pacman:
    update_cache: yes
    upgrade: yes


- name: Installing packages from Official Arch Repo
  pacman:
    name: "{{ OFFICIAL_PACKAGES_AVAILABLE }}"
    state: present


- name: Updating final cache and packages
  pacman:
    update_cache: yes
    upgrade: yes
