---
- name: Create user for aur_builder
  user:
    name: aur_builder
    group: wheel


- name: Giving permissions to aur_builder
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'


- name: Updating cache and packages
  aur:
    upgrade: yes
    use: pacaur
  become: true
  become_user: aur_builder


- name: Installing packages from Official Arch Repo
  aur:
    name: "{{ UNOFFICIAL_PACKAGES_AVAILABLE }}"
    skip_installed: true
    use: pacaur
  become: true
  become_user: aur_builder


- name: Updating final cache and packages
  aur:
    upgrade: yes
    use: pacaur
  become: true
  become_user: aur_builder
